import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const ui=fs.readFileSync(new URL('../saas-light.css',import.meta.url),'utf8');
assert.match(html,/pedido-busca-dropdown/,'busca deve abrir lista interna');
assert.match(html,/q\s*&&\s*fp\.length/,'lista só aparece quando há busca');
assert.match(html,/Itens do Pedido/,'itens escolhidos devem ter bloco principal');
assert.match(html,/pedido-itens-tabela/,'itens escolhidos devem usar tabela ampla');
assert.match(ui,/\.pedido-itens-principal/,'CSS deve ampliar itens do pedido');
assert.match(ui,/\.pedido-busca-dropdown/,'CSS deve tratar resultados como dropdown');
console.log('PEDIDO_UI_OK');
